services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
      # isnt this just self healing in k8s
    restart: unless-stopped #always restarts the container unless it is manally stopped (in the case of a crash)
    # environment:
      # Optional: put your config options customization here. Examples:
      # ND_LOGLEVEL: debug
    volumes:
      - "./data:/data"
      - "./music:/music:ro"
